import {
  IsString,
  IsUUID,
  IsInt,
  IsArray,
  IsOptional,
  ValidateNested,
  Min,
  IsDateString,
  IsNotEmpty,
} from 'class-validator';

import { Type } from 'class-transformer';
import {
  ApiProperty,
  ApiPropertyOptional,
} from '@nestjs/swagger';

export class SubtitleDto {
  @ApiProperty({
    description: 'Unique identifier of the subtitle',
    example: 'bcae7d8e-38dd-4e17-89e7-8e08f4d69abc',
  })
  @IsUUID()
  id!: string;

  @ApiProperty({
    description: 'Subtitle title',
    example: 'Introduction',
  })
  @IsString()
  @IsNotEmpty()
  title!: string;

  @ApiProperty({
    description: 'Subtitle content',
    example: 'This is the updated content.',
  })
  @IsString()
  content!: string;

  @ApiProperty({
    description: 'Title of the subtitle when the client began editing',
    example: 'Introduction',
  })
  @IsString()
  base_title!: string;

  @ApiProperty({
    description: 'Content of the subtitle when the client began editing',
    example: 'Original content',
  })
  @IsString()
  base_content!: string;

  @ApiPropertyOptional({
    description: 'Subtitle creation timestamp',
    example: '2026-10-03T10:00:00.000Z',
  })
  @IsOptional()
  @IsDateString()
  created_at?: string;

  @ApiPropertyOptional({
    description: 'Subtitle last update timestamp',
    example: '2026-10-03T11:00:00.000Z',
  })
  @IsOptional()
  @IsDateString()
  updated_at?: string;

  @ApiPropertyOptional({
    description: 'Current subtitle version',
    example: 3,
    minimum: 1,
  })
  @IsOptional()
  @IsInt()
  @Min(1)
  version?: number;

  @ApiProperty({
    description: 'Subtitle version on which the client based its edit',
    example: 2,
    minimum: 1,
  })
  @IsInt()
  @Min(1)
  base_version!: number;
}

export class CreateDocumentDto {
  @ApiPropertyOptional({
    description: 'Document UUID. May be omitted if generated by the server.',
    example: '7e1c8d65-0c51-4b3f-a7b8-123456789abc',
  })
  @IsOptional()
  @IsUUID()
  uuid?: string;

  @ApiProperty({
    description: 'Notebook title',
    example: 'My Collaborative Notebook',
  })
  @IsString()
  @IsNotEmpty()
  title!: string;

  @ApiProperty({
    description: 'Subtitles belonging to the notebook',
    type: () => SubtitleDto,
    isArray: true,
  })
  @IsArray()
  @ValidateNested({ each: true })
  @Type(() => SubtitleDto)
  subtitles!: SubtitleDto[];

  @ApiPropertyOptional({
    description: 'Identifier of the device creating the document',
    example: 'device-001',
  })
  @IsOptional()
  @IsString()
  deviceId?: string;
}